### PR TITLE
Add basic CI

### PR DESCRIPTION
**Pull request by oeb25**
This adds basic CI which, currently, sets up Rust on Linux only and runs `./ci/scripts/all`.

### CODE REVIEW

**Comment by oeb25** [comment]
Seems like the test `widgets::thesaurus::tests::build_dict` relies on `data/english-wordnet-2022-subset.ttl` which is fetched by `just configure`.

What would be a good way to get this file without running `just configure`?

One option would be to pull out thesaurus as a new crate and have it download `english-wordnet-2022-subset.ttl` as part of its `build.rs` and put it in [`OUT_DIR`](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts), potentially only for `test` builds if we still want it to be configurable in the API?

Very open to other options as well!

**Comment by mikkeldenker** [comment]
I think it would be okay to just skip that test if `english-wordnet-2022-subset.ttl` isn't present. There are also some other tests which rely e.g. on the dual encoder model that are skipped if it isn't downloaded (`test_dual_encoder` in file `crates/core/src/summarizer.rs`).

Generally I think we should strive to write the tests so they don't need external data, but for the ones where we really test some functionality end-to-end they should just be skipped if the data hasn't been downloaded.

**Comment by oeb25** [comment]
Finally passed! 🎉 

I think I want to make some changes, but this should be sufficient for merging.

The changes I'm proposing are:
- **Split into more jobs**: Currently everything is done linearly, but a few of the steps are independent:
   - `cargo check`/`cargo test`. We might even consider splitting this into two jobs since we have to wait for `cargo check` to finish before starting `cargo test`, which seems to not reuse much of the work done previously.
   - `npm run check`.
   - `cargo about`/license checking (this should probably be altered in some way, as currently it just emits the file and does nothing with it).
- **Use [`cargo nextest`](https://nexte.st/index.html)**

I know these changes will move some of the logic into the workflow and be GitHub Actions specific, but I think that's worth the price, since it's not too bad to translate to other CI systems, and the project will likely stay on GitHub for a while (I presume). But I understand if it is desirable to keep most of the logic external.

We can open a new PR if we want to experiment with any of these changes, but this should be good to merge!

**Review by mikkeldenker — APPROVED** [review]
This is such a giant quality of life improvement, thank you!

I think your proposed changes sound entirely reasonable. I just want us to be a bit mindful in general about the github action specific features we use so we don't suddenly have a hard dependency on github for the CI, but the changes you proposed seem totally fine to me.

**Pull request merged**
